//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantesActividades
    {
        public int Consecutivo { get; set; }
        public int ConsecutivoActividad { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
    
        public virtual tbActividad tbActividad { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
