//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbActividad()
        {
            this.EstudiantesActividades = new HashSet<EstudiantesActividades>();
        }
    
        public int Consecutivo { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int ConsecutivoEstado { get; set; }
        public string Imagen { get; set; }
    
        public virtual tbEstados tbEstados { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiantesActividades> EstudiantesActividades { get; set; }
    }
}
