//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_WEB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbActividad
    {
        public int Consecutivo { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int Estado { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
