//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrito
    {
        public int ConsecutivoCarrito { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int ConsecutivoProducto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }
    
        public virtual tbProducto tbProducto { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
