//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalle
    {
        public int ConsecutivoDetalle { get; set; }
        public int ConsecutivoFactura { get; set; }
        public int ConsecutivoProducto { get; set; }
        public decimal PrecioUnitarioPagado { get; set; }
        public int CantidadUnidades { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public decimal Impuesto { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
