//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFactura()
        {
            this.tbDetalle = new HashSet<tbDetalle>();
        }
    
        public int ConsecutivoFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int CantidadProductos { get; set; }
        public decimal TotalPagado { get; set; }
        public string MetodoPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalle> tbDetalle { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
